"""
Planner Node
============
Converts the structured LLM diagnosis (produced by diagnose_node via Log MCP)
into an actionable remediation plan.

The planner calls the Groq LLM with the full log summary context
and the diagnosis to determine the best remediation.
"""

import sys
import os
import json
import logfire
from groq import Groq

# Add parent directory to path to allow importing state
parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

# Add root directory for config import
root_dir = os.path.dirname(parent_dir)
if root_dir not in sys.path:
    sys.path.append(root_dir)

from state import AgentState
import config


def planner_node(state: AgentState) -> AgentState:
    """
    Planner node.

    Calls the LLM with the full log summary + alert context + diagnosis
    to generate a remediation plan.
    """
    diagnosis_raw = state.get("diagnosis", "{}")
    log_summary = state.get("log_summary", {})
    alert = state.get("alert", {})

    with logfire.span("🧠 planner_node", diagnosis=diagnosis_raw):
        logfire.info("🤔 Planning remediation based on Log MCP diagnosis...")
        print("🧠 ---PLANNING REMEDIATION---")

        # ── Parse the LLM diagnosis produced by diagnose_node ───────────────
        try:
            diagnosis = json.loads(diagnosis_raw) if isinstance(diagnosis_raw, str) else diagnosis_raw
        except json.JSONDecodeError:
            diagnosis = {}

        logfire.info("🤔 Calling LLM for plan...")

        client = Groq(api_key=config.GROQ_API)

        context = {
            "alert": alert,
            "log_summary": log_summary,
            "diagnosis": diagnosis,
        }

        prompt = f"""You are a senior DevOps engineer. Given the following Docker container alert, log analysis, and diagnosis, determine the best remediation strategy.

Context:
{json.dumps(context, indent=2)}

Available Docker tools:
  - start_container (arguments: container_id)
  - stop_container (arguments: container_id)
  - restart_container (arguments: container_id)
  - remove_container (arguments: container_id, force)
  - list_containers (arguments: all)
  - get_container_logs (arguments: container_id, tail)

Return ONLY valid JSON with this exact structure:
{{
  "steps": [
    {{
      "tool": "<tool_name>",
      "arguments": {{
        "<arg_name>": "<arg_value>"
      }}
    }}
  ]
}}"""

        response = client.chat.completions.create(
            model=config.MODEL_120B,
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"},
        )

        content = response.choices[0].message.content
        try:
            plan_data = json.loads(content)
            state["plan"] = json.dumps(plan_data)
            logfire.info("📝 Plan generated by LLM", plan=plan_data)
            print(f"📝 Generated Plan:\n{json.dumps(plan_data, indent=2)}")
        except json.JSONDecodeError:
            state["plan"] = content
            logfire.warn("⚠️ LLM returned non-JSON plan", raw_output=content)
            print(f"⚠️  Generated Plan (raw): {content}")

    return state


